# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: RBP Admin
  admin_email: admin@hopemediahouse.com
  admin_password: infamous1
  gmail_username: owen.hope@gmail.com
  gmail_password: infamous#1988
  secret_key_base: 7342b8e18d31de8743ea707c20ba1ec06049ecb1424b6d47afe40c085acaede18d75ddc05978f4fd55b11e97e7b0175d4c889abe98acb1d6eab56247ff0df439

test:
  secret_key_base: 7342b8e18d31de8743ea707c20ba1ec06049ecb1424b6d47afe40c085acaede18d75ddc05978f4fd55b11e97e7b0175d4c889abe98acb1d6eab56247ff0df439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
