# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_first_name: RBP
  admin_last_name: Admin
  admin_phone: 222-222-2222
  admin_email: admin@hopemediahouse.com
  admin_password: infamous1
  gmail_username: owen.hope@gmail.com
  gmail_password: infamous#1988
  secret_key_base: 841f3bf428c048a036d71be5aa5a3725ec5944ad1c0f080c9ae6797810303b4534cc50a42bc8894ad358c04dc8e9e9b4764ff6500c9b4e2f88fd1edf870ad898

test:
  secret_key_base: 841f3bf428c048a036d71be5aa5a3725ec5944ad1c0f080c9ae6797810303b4534cc50a42bc8894ad358c04dc8e9e9b4764ff6500c9b4e2f88fd1edf870ad898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_first_name: <%= ENV["ADMIN_FIRST_NAME"] %>
  admin_last_name: <%= ENV["ADMIN_LAST_NAME"] %>
  admin_phone: <%= ENV["ADMIN_PHONE"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
